env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  project: './tsconfig.json'
plugins:
  - react
  - import
rules:
  {
    'no-unused-vars': 'off',
    '@typescript-eslint/no-unused-vars':
      ['error', { 'vars': 'all', 'args': 'after-used', 'ignoreRestSiblings': false }],
    'import/extensions': ['error', 'ignorePackages', { 'js': 'never', 'jsx': 'never', 'ts': 'never', 'tsx': 'never' }],
  }
settings: { 'import/resolver': { 'node': { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] } } }
